export const menuTypes = {    
    GET_MENUS: 'GET-MENUS',
    GET_PARENT_MENUS: 'GET-PARENT-MENUS',
    GET_CHILD_MENUS: 'GET-CHILD-MENUS',
    CREATE: 'CREATE-MENU',
    UPDATE: 'UPDATE-MENU',
    DELETE: 'DELETE-MENU'
}